### ISSUE TITLE
Meta form/question methods

### ISSUE THREAD

**Issue by sjgllghr** [NorthwestGreenChemistry/PrISM#37]
- [x] check if a section has any answers
- [ ] get unanswered questions
- [ ] step 1 rank priorities
- [ ] step 7 refer to step 1
- [ ] pdf formatting to help pdf.js

**Comment by sjgllghr** [comment]
Created #65 and #66 to cover remaining.
